<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ut4Recon.Core\Ut4Recon.Core.csproj" />
    <ProjectReference Include="..\Ut4Recon.Geometry\Ut4Recon.Geometry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UAssetAPI" Version="1.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
